name: image_picker_web_totalxsoftware
description: "A Flutter web plugin for selecting and uploading images to Firebase Storage with support for single and multiple image selection, optimized upload options, and custom error handling."
version: 1.0.0
homepage: https://github.com/totalxsoftwaredevelopers/image_picker_web_totalxsoftware.git

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  image_picker_web: ^4.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  generate: true
  assets:
    - assets/

  plugin:
    platforms:
      web:

screenshots:
  - description: "www.totalx.in"
    path: assets/images/totalx.png